USE [master]
GO
/****** Object:  Database [DWFarmacias]    Script Date: 4/11/2020 5:20:35 PM ******/
CREATE DATABASE [DWFarmacias]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'DWFarmacias', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\DWFarmacias.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'DWFarmacias_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\DWFarmacias_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [DWFarmacias] SET COMPATIBILITY_LEVEL = 140
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DWFarmacias].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [DWFarmacias] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [DWFarmacias] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [DWFarmacias] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [DWFarmacias] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [DWFarmacias] SET ARITHABORT OFF 
GO
ALTER DATABASE [DWFarmacias] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [DWFarmacias] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [DWFarmacias] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [DWFarmacias] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [DWFarmacias] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [DWFarmacias] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [DWFarmacias] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [DWFarmacias] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [DWFarmacias] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [DWFarmacias] SET  DISABLE_BROKER 
GO
ALTER DATABASE [DWFarmacias] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [DWFarmacias] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [DWFarmacias] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [DWFarmacias] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [DWFarmacias] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [DWFarmacias] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [DWFarmacias] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [DWFarmacias] SET RECOVERY FULL 
GO
ALTER DATABASE [DWFarmacias] SET  MULTI_USER 
GO
ALTER DATABASE [DWFarmacias] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [DWFarmacias] SET DB_CHAINING OFF 
GO
ALTER DATABASE [DWFarmacias] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [DWFarmacias] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [DWFarmacias] SET DELAYED_DURABILITY = DISABLED 
GO
EXEC sys.sp_db_vardecimal_storage_format N'DWFarmacias', N'ON'
GO
ALTER DATABASE [DWFarmacias] SET QUERY_STORE = OFF
GO
USE [DWFarmacias]
GO
/****** Object:  Table [dbo].[DimLoja]    Script Date: 4/11/2020 5:20:35 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DimLoja](
	[IdLoja] [int] NOT NULL,
	[Loja] [nvarchar](50) NULL,
 CONSTRAINT [PK_DimLoja] PRIMARY KEY CLUSTERED 
(
	[IdLoja] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[DimProduto]    Script Date: 4/11/2020 5:20:35 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DimProduto](
	[IDProduto] [int] NOT NULL,
	[NomeProduto] [nvarchar](50) NULL,
 CONSTRAINT [PK_DimProduto] PRIMARY KEY CLUSTERED 
(
	[IDProduto] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[DimTempo]    Script Date: 4/11/2020 5:20:35 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DimTempo](
	[IdData] [int] NOT NULL,
	[Ano] [int] NULL,
	[NumeroTrimestre] [int] NULL,
	[NomeTrimestre] [nvarchar](20) NULL,
	[NumeroMes] [int] NULL,
	[NomeMes] [nvarchar](20) NULL,
	[DiadoMes] [int] NULL,
	[DiadaSemana] [nvarchar](50) NULL,
 CONSTRAINT [PK_DimTempo] PRIMARY KEY CLUSTERED 
(
	[IdData] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[fVenda]    Script Date: 4/11/2020 5:20:35 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[fVenda](
	[IDProduto] [int] NOT NULL,
	[IDData] [int] NOT NULL,
	[IDLoja] [int] NOT NULL,
	[UnidadesVendidas] [int] NULL,
	[ValorVenda] [smallmoney] NULL,
 CONSTRAINT [PK_fVenda] PRIMARY KEY CLUSTERED 
(
	[IDProduto] ASC,
	[IDData] ASC,
	[IDLoja] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[fVenda]  WITH CHECK ADD  CONSTRAINT [FK_fVenda_DimLoja] FOREIGN KEY([IDLoja])
REFERENCES [dbo].[DimLoja] ([IdLoja])
GO
ALTER TABLE [dbo].[fVenda] CHECK CONSTRAINT [FK_fVenda_DimLoja]
GO
ALTER TABLE [dbo].[fVenda]  WITH CHECK ADD  CONSTRAINT [FK_fVenda_DimProduto] FOREIGN KEY([IDProduto])
REFERENCES [dbo].[DimProduto] ([IDProduto])
GO
ALTER TABLE [dbo].[fVenda] CHECK CONSTRAINT [FK_fVenda_DimProduto]
GO
ALTER TABLE [dbo].[fVenda]  WITH CHECK ADD  CONSTRAINT [FK_fVenda_DimTempo] FOREIGN KEY([IDData])
REFERENCES [dbo].[DimTempo] ([IdData])
GO
ALTER TABLE [dbo].[fVenda] CHECK CONSTRAINT [FK_fVenda_DimTempo]
GO
USE [master]
GO
ALTER DATABASE [DWFarmacias] SET  READ_WRITE 
GO
